### ISSUE TITLE
Error when accessing blog

### ISSUE THREAD

**Issue by microcurse** [JeyKeu/branch#13]
First of all, thanks so much for this starter theme. I've been working on getting Sass and Bootstrap working on the Timber Starter theme for over a week now lol.

Anyway, I seem to have come across a fatal error when attempting to access the blog. Below is the error message. Any help is greatly appreciated!

Fatal error: Uncaught Error: Call to undefined method Timber\TextHelper::remove_tags() in M:\Docs\Web\MAMP\htdocs\portfolio-site\wp-content\plugins\timber-library\lib\Post.php:437 Stack trace: #0 M:\Docs\Web\MAMP\htdocs\portfolio-site\wp-content\themes\branch\vendor\twig\twig\lib\Twig\Template.php(672): Timber\Post->get_preview() #1 M:\Docs\Web\MAMP\htdocs\portfolio-site\wp-content\themes\branch\vendor\twig\twig\lib\Twig\Environment.php(462) : eval()'d code(43): Twig_Template->getAttribute(Object(Timber\Post), 'get_preview', Array) #2 M:\Docs\Web\MAMP\htdocs\portfolio-site\wp-content\themes\branch\vendor\twig\twig\lib\Twig\Template.php(215): __TwigTemplate_bbc3cacb8969617e11e3317dc42d4889458c1c96cdf9bb3ad0fbff9a7cffbff2->block_content(Array, Array) #3 M:\Docs\Web\MAMP\htdocs\portfolio-site\wp-content\themes\branch\vendor\twig\twig\lib\Twig\Environment.php(462) : eval()'d code(27): Twig_Template->displayBlock('content', Array, Array) #4 M:\Docs\Web\MAMP\htdocs\portfolio-site\wp-content\themes\branch\vendor\twig\twig\lib\Tw in M:\Docs\Web\MAMP\htdocs\portfolio-site\wp-content\plugins\timber-library\lib\Post.php on line 437

**Comment by maxdmyers** [comment]
Can you provide any other details? I tried to reproduce but was unable. I took the following steps:

1. Installed WordPress
2. cd 'd into themes directory and ran composer create-project jeykeu/branch branch
3. cd 'd into branch and ran gulp
4. Activated theme in dashboard
5. Tested the home page and post page in the browser

**Comment by ereinach** [comment]
I am having the exact same problem.

Gulp is running. MAMP is running. GULP is mapped to MAMP, wp-admin shows up, I can activate the theme. But when I get back to the public side, I get the exact same error

**Comment by ereinach** [comment]
I installed the default TIMBER stater theme, and everything work fine.

**Comment by JunaidQadirB** [comment]
I'm using WAMP on Windows and works fine. I'll have to check it on a Mac then can confirm whether there is any issue with branch or it might be something else. Please feel free to update this thread, I'm leaving it open.

**Comment by jasalt** [comment]
I hit this error on Ubuntu (VVV Vagrant box) when I had `timber-library` plugin installed beforehand. Deactivating that made the theme load fine.

**Comment by ereinach** [comment]
Hey @JeyKeu, I see that you closed this, but here is the actual fix:

https://timber.github.io/docs/reference/timber-post/

**get_preview**
DEPRECATED since 1.3.1, use {{ post.preview }} instead

Your templates crash when get_preview is being used while using the newer version of timber.

hope it helps, I'll do a pull request

**Comment by JunaidQadirB** [comment]
@ereinach Thanks for point that out. Please do.
