### ISSUE TITLE
Wondering where is it written that you imported the bootstrap files?

### ISSUE THREAD

**Issue by mamarilmanson** [JeyKeu/branch#8]
The title says it and if it's online how will I be able to make available offline... first time I will try to use this starter so I'm a bit lost... thank you... :)

**Comment by JunaidQadirB** [comment]
We are using node to manage client dependencies.
Please see the [package.json](https://github.com/JeyKeu/branch/blob/master/package.json).
I hope what you are asking.

**Comment by mamarilmanson** [comment]
oh... ok... so I need to be always online in order to use it properly?

**Comment by JunaidQadirB** [comment]
no you don't have to be online. I'm not sure whats your workflow like.
