### ISSUE TITLE
Cant parse package.json

### ISSUE THREAD

**Issue by ghost** [JeyKeu/branch#9]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Konas\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.10.8
3 info using node@v6.4.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly rollbackFailedOptional Starting
8 silly rollbackFailedOptional Finishing
9 silly runTopLevelLifecycles Finishing
10 silly install printInstalled
11 verbose stack Error: Failed to parse json
11 verbose stack Unexpected token '"' at 13:3
11 verbose stack   "engines": {
11 verbose stack   ^
11 verbose stack     at parseError (C:\Users\Konas\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:390:11)
11 verbose stack     at parseJson (C:\Users\Konas\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:79:23)
11 verbose stack     at C:\Users\Konas\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:48:5
11 verbose stack     at C:\Users\Konas\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
11 verbose stack     at tryToString (fs.js:455:3)
11 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
12 verbose cwd P:\Arbejde\Laravel\bodymindbalance\wp-content\themes\bodymindbalance
13 error Windows_NT 10.0.14393
14 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Konas\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
15 error node v6.4.0
16 error npm  v3.10.8
17 error file P:\Arbejde\Laravel\bodymindbalance\wp-content\themes\bodymindbalance\package.json
18 error code EJSONPARSE
19 error Failed to parse json
19 error Unexpected token '"' at 13:3
19 error   "engines": {
19 error   ^
20 error File: P:\Arbejde\Laravel\bodymindbalance\wp-content\themes\bodymindbalance\package.json
21 error Failed to parse package.json data.
21 error package.json must be actual JSON, not just JavaScript.
21 error
21 error This is not a bug in npm.
21 error Tell the package author to fix their package.json file. JSON.parse
22 verbose exit [ 1, true ]

You forgot to end the maintainers array.

**Comment by JunaidQadirB** [comment]
https://github.com/JeyKeu/branch/commit/42d9941546e8441ec3504d4c90f3d86d6da1a9a4  fixed.

Thanks.
